// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DatabaseDungeon",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "DatabaseDungeon",
            targets: ["AppModule"],
            bundleIdentifier: "com.bhargav.DatabaseDungeon",
            teamIdentifier: "73U762R3G4",
            displayVersion: "1.0",
            bundleVersion: "1",
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "App"
        )
    ]
)